services:
  bot:
    image: mewtwo2387/silverwolf-bot:latest
    build: .
    container_name: silverwolf-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "127.0.0.1:8080:6769"
    volumes:
      - ./persistence:/app/persistence
    mem_limit: 1g
    memswap_limit: 1g
