const userTable = {
  name: 'User',
  columns: [
    { name: 'id', type: 'VARCHAR PRIMARY KEY' },
    { name: 'credits', type: 'INTEGER DEFAULT 0' },
    { name: 'bitcoin', type: 'FLOAT DEFAULT 0' },
    { name: 'last_bought_price', type: 'FLOAT DEFAULT 0' },
    { name: 'last_bought_amount', type: 'FLOAT DEFAULT 0' },
    { name: 'total_bought_price', type: 'FLOAT DEFAULT 0' },
    { name: 'total_bought_amount', type: 'FLOAT DEFAULT 0' },
    { name: 'total_sold_price', type: 'FLOAT DEFAULT 0' },
    { name: 'total_sold_amount', type: 'FLOAT DEFAULT 0' },
    { name: 'dinonuggies', type: 'INTEGER DEFAULT 0' },
    { name: 'dinonuggies_last_claimed', type: 'DATETIME DEFAULT NULL' },
    { name: 'dinonuggies_claim_streak', type: 'INTEGER DEFAULT 0' },
    { name: 'multiplier_amount_level', type: 'INTEGER DEFAULT 1' },
    { name: 'multiplier_rarity_level', type: 'INTEGER DEFAULT 1' },
    { name: 'beki_level', type: 'INTEGER DEFAULT 1' },
    { name: 'birthdays', type: 'DATETIME DEFAULT NULL' },
    { name: 'ascension_level', type: 'INTEGER DEFAULT 1' },
    { name: 'heavenly_nuggies', type: 'INTEGER DEFAULT 0' },
    { name: 'nuggie_flat_multiplier_level', type: 'INTEGER DEFAULT 1' },
    { name: 'nuggie_streak_multiplier_level', type: 'INTEGER DEFAULT 1' },
    { name: 'nuggie_credits_multiplier_level', type: 'INTEGER DEFAULT 1' },
    { name: 'pity', type: 'INTEGER DEFAULT 0' },
    { name: 'slots_times_played', type: 'INTEGER DEFAULT 0' },
    { name: 'slots_amount_gambled', type: 'FLOAT DEFAULT 0' },
    { name: 'slots_times_won', type: 'INTEGER DEFAULT 0' },
    { name: 'slots_amount_won', type: 'FLOAT DEFAULT 0' },
    { name: 'slots_relative_won', type: 'FLOAT DEFAULT 0' },
    { name: 'blackjack_times_played', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_amount_gambled', type: 'FLOAT DEFAULT 0' },
    { name: 'blackjack_times_won', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_times_drawn', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_times_lost', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_amount_won', type: 'FLOAT DEFAULT 0' },
    { name: 'blackjack_relative_won', type: 'FLOAT DEFAULT 0' },
    { name: 'roulette_times_played', type: 'INTEGER DEFAULT 0' },
    { name: 'roulette_amount_gambled', type: 'FLOAT DEFAULT 0' },
    { name: 'roulette_times_won', type: 'INTEGER DEFAULT 0' },
    { name: 'roulette_amount_won', type: 'FLOAT DEFAULT 0' },
    { name: 'roulette_relative_won', type: 'FLOAT DEFAULT 0' },
    { name: 'roulette_streak', type: 'INTEGER DEFAULT 0' },
    { name: 'roulette_max_streak', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_streak', type: 'INTEGER DEFAULT 0' },
    { name: 'blackjack_max_streak', type: 'INTEGER DEFAULT 0' },
    { name: 'dinonuggie_last_gambled', type: 'DATETIME DEFAULT NULL' },
    { name: 'nuggie_pokemon_multiplier_level', type: 'INTEGER DEFAULT 1' },
    { name: 'nuggie_nuggie_multiplier_level', type: 'INTEGER DEFAULT 1' },
    { name: 'stellar_nuggies', type: 'INTEGER DEFAULT 0' },
    { name: 'last_murder', type: 'DATETIME DEFAULT NULL' },
    { name: 'murder_success', type: 'INTEGER DEFAULT 0' },
    { name: 'murder_fail', type: 'INTEGER DEFAULT 0' },
  ],
  primaryKey: ['id'],
  specialConstraints: [],
  constraints: [],
};

module.exports = userTable; 